### PR TITLE
Remove quotes from paths in nativescript-build.xcconfig

### LINKED ISSUE #446: TNS_TYPESCRIPT_DECLARATIONS_PATH places d.ts files in wrong directory
Uncommenting the line in `nativescript-build.xcconfig`:
```
TNS_TYPESCRIPT_DECLARATIONS_PATH = "$(SRCROOT)/typescript-declarations"
```

Places the generated d.ts files at 
```
YOUR_APP/platforms/ios/internal/metadata-generator/bin/"/Users/username/...a..bunch..of..folders/platforms/ios/typescript-declarations"
```

rather than the expected:
```
YOUR_APP/platforms/ios/typescript-declarations
```

### PR DESCRIPTION
**Pull request by speigg**
Fixes #446

### CODE REVIEW

**Comment by jasssonpet** [comment]
Hello, @speigg,

Would you be so kind to update this PR by remove the quotes from the [`TNS_DEBUG_METADATA_PATH` var](  https://github.com/speigg/ios-runtime/blob/67be31d25460b911d94d4c9bea447d598a9dfb51/build/project-template/internal/nativescript-build.xcconfig#L16) as well.

**Comment by speigg** [comment]
I would have done that, except when I tried it myself it didn't seem to
output the metadata file at the expected location (I didn't see it
anywhere, though I also didn't look very hard since I don't need the debug
metadata).

**Comment by speigg** [comment]
Hmm, actually, the `TNS_DEBUG_METADATA_PATH` var seems to work fine without quotes, I must have been doing something else wrong. I'll go ahead and update the PR.

**Comment by jasssonpet** [comment]
Thank you :beer:

**Pull request merged**
