### PR TITLE
Update WebKit from iOS 12.0 tag

### PR DESCRIPTION
**Pull request by mbektchiev**

### CODE REVIEW

**Comment by mbektchiev** [comment]
run ci

**Comment by mbektchiev** [comment]
test

**Comment by Natalia-Hristova** [comment]
test --performance

**Comment by Natalia-Hristova** [comment]
test --performance

**Comment by Natalia-Hristova** [comment]
test --performance

**Comment by Natalia-Hristova** [comment]
test --performance

**Comment by Natalia-Hristova** [comment]
test --performance

**Comment by Natalia-Hristova** [comment]
test --performance

**Comment by Natalia-Hristova** [comment]
test --performance

**Comment by Natalia-Hristova** [comment]
test --performance

**Comment by Natalia-Hristova** [comment]
test --performance

**Comment by Natalia-Hristova** [comment]
test --performance

**Comment by Natalia-Hristova** [comment]
test --performance

**Comment by Natalia-Hristova** [comment]
test --performance

**Comment by Natalia-Hristova** [comment]
test

**Pull request merged**
