### PR TITLE
Moving tns_modules inside app folder.

### PR DESCRIPTION
**Pull request by jasssonpet**

### CODE REVIEW

**Comment by jasssonpet** [comment]
Ping @Fatme @atanasovg @dtopuzov

**Comment by fealebenpae** [comment]
Since this is a breaking change for the CI builds and the CLI we'd like to receive confirmation of acknowledgement before we move forward with merging it.

This also means that the CI build for this patch will fail (as it has), even though this is a good patch.

**Comment by jasssonpet** [comment]
Changed to be backwards compatible so it can be merged now.

**Comment by PanayotCankov** [comment]
:+1:

**Pull request merged**
