### PR TITLE
Update to latest greatest JavaScriptCore

### PR DESCRIPTION
**Pull request by fealebenpae**
Some of the highlights in this version:
- Rethrowing JavaScriptErrors preserves the original stacktrace
- Initial arrow functions support
- Some destructuring and rest syntax
- Updated Promise implementation

### CODE REVIEW

**Comment by fealebenpae** [comment]
ping @jasssonpet 
Does this merit inclusion in the current release? They new way of working with JavaScript exceptions in C++ might impact your `NSError **` work later on.

**Comment by fealebenpae** [comment]
ping @KristinaKoeva 
The Inspector frontend and host app will need updating once this lands.

**Comment by jasssonpet** [comment]
:+1: After our tests (and modules tests) pass.

**Comment by fealebenpae** [comment]
ping @dtopuzov 
Would it be possible to run the cross-platforms modules' tests against this PR?

**Comment by dtopuzov** [comment]
run ci

**Pull request merged**
