### PR TITLE
Export all public symbols from JavaScriptCore C API

### PR DESCRIPTION
**Pull request by ivanbuhov**
Requirement for https://github.com/NativeScript/ios-runtime/issues/607
Also related to: https://github.com/NativeScript/sample-ios-embedded/pull/1

### CODE REVIEW

**Comment by jasssonpet** [comment]
Can we somehow export all symbols marked with `JS_EXPORT` instead?

**Comment by ivanbuhov** [comment]
@jasssonpet According to [this guy](http://stackoverflow.com/a/32548642/3968054) there is no easy way for a dynamic library to automatically reexport symbols defined in a static library after linking against it.
A possible solution is to filter only needed symbols with the help of `Clang`/`metadata generator` or using `nm` and some regex magic and dump the result in a [exports file](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPFrameworks/Tasks/ExportingInterfaces.html).
Since this is not related to https://github.com/NativeScript/ios-runtime/issues/607 I suggest to treat it as a separate issue.

**Comment by fealebenpae** [comment]
You could, I don't know, use this [list of symbols JavaScriptCore exports](https://github.com/WebKit/webkit/blob/master/Source/JavaScriptCore/JavaScriptCore.order) 😉

**Comment by jasssonpet** [comment]
We can export the full public JSC API: https://gist.github.com/anonymous/aab759df6c372085c72c214acc95b575

What do you think about building the JavaScriptCore as a shared framework then.

**Comment by fealebenpae** [comment]
Building as a framework would needlessly complicate matters with private headers and fat binaries. IMO you can even manually hardcode the list of symbols in the public C API - they are few enough and a new one gets added once in a blue moon. But personally I would just use the order file.

**Comment by ivanbuhov** [comment]
@fealebenpae It seems that not all of the symbols in the list are included in the static binary. For example `JSC::ArrayProfile::computeUpdatedPrediction(JSC::CodeBlock*, JSC::OperationInProgress)` is present in the `JavaScriptCore.order` file but there is no such method in the source and no such symbol available in the static library. I guess there is a good reason for these inconsistencies and maybe we can handle them in such a way but still IMO exporting all APIs included in the list is a bit overkill.

Since we have no use cases that require dynamic library nor exporting all of the JSC APIs I am voting for manually listing only the public JSC APIs :)

**Comment by jasssonpet** [comment]
You can put them in a separate file if you'd like similarly to https://github.com/NativeScript/ios-runtime/blob/buhov/embeding-ios-runtime-fix/tests/TestFixtures/exported-symbols.txt

**Comment by jasssonpet** [comment]
run ci

**Comment by jasssonpet** [comment]
run ci

**Comment by jasssonpet** [comment]
run ci

**Comment by pkoleva** [comment]
run ci

**Comment by pkoleva** [comment]
run ci

**Comment by pkoleva** [comment]
run ci

**Comment by jasssonpet** [comment]
run ci

**Pull request merged**
