### PR TITLE
Integrate the WebInspector Profiler

### PR DESCRIPTION
**Pull request by KristinaKoeva**
Add TimelinesAgent that would let us profile function calls. Hook console.profile and console.profileEnd to TimelinesAgent methods. 
Update inspector frontend to a version that works in Nightly only
Issue #164

### CODE REVIEW

**Comment by jasssonpet** [comment]
run ci

**Comment by jasssonpet** [comment]
run ci

**Comment by fealebenpae** [comment]
:+1:

**Comment by fealebenpae** [comment]
run ci

**Pull request merged**
