### PR TITLE
build for iOS - KeyError: 'DEPLOYMENT_TARGET_CLANG_FLAG_NAME'

### PR DESCRIPTION
**Pull request by fpattis**
pull request based on this issue: https://github.com/NativeScript/NativeScript/issues/9840 and this patch: https://github.com/NativeScript/ns-v8ios-runtime/commit/1e0c0cec0e9627cd72652208347e760809f7d1e1

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it. - https://github.com/NativeScript/NativeScript/issues/9840
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/ios-runtime/blob/master/CONTRIBUTING.md#contribute-to-the-code-base
- [ ] Tests for the changes are included.

## What is the new behavior?

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Review by NathanWalker — APPROVED** [review]

**Comment by NathanWalker** [comment]
@fpattis thank you! when you get a chance, do you mind signing the CLA?

**Comment by fpattis** [comment]
> @fpattis thank you! when you get a chance, do you mind signing the CLA?

@NathanWalker I signed it. Thanks.

**Comment by rod750** [comment]
@cla-bot check

**Comment by richardman1** [comment]
When is this getting released in ios 6.5.5 version? I really need it

**Pull request merged**
