### PR TITLE
Better error reporting

### PR DESCRIPTION
**Pull request by jasssonpet**

### CODE REVIEW

**Comment by fealebenpae** [comment]
Let's try to somehow delineate the native and the JS stack traces. How about if`reportFatalErrorBeforeShutdown` printed something like `Uncaught JavaScript Error`, then `native stacktrace:` and lastly `actual JavaScript error:`? Right now we're lumping the two stack traces together and it's hard to tell which is which from a new user's perspective.

**Comment by jasssonpet** [comment]
What will the difference between "uncaught" and "actual" error be?

**Comment by fealebenpae** [comment]
What I meant to say is that we should have a heading of some sort, like:
```
NativeScript detected uncaught JavaScript error.
Native stack trace:
// native stack trace follows
Actual error:
// JavaScript error & stack printed here
```

**Comment by jasssonpet** [comment]
Ok. Btw, is there an easy way to mix the native and JS stack, like the inspector does. I looked at their code but it seems that it is private and the best we can do is to copy-paste it.

**Comment by fealebenpae** [comment]
Well, that sounds promising. Could you please post an example here of how it would look?

**Comment by jasssonpet** [comment]
Here is how it looks now:

```
***** Fatal JavaScript exception - application has been terminated. *****
file:///app/index.js:2:29: JS ERROR Error: sample error
 0 throwErrorFunction@file:///app/index.js:2:29
 1 applicationDidFinishLaunchingWithOptions@file:///app/index.js:12:27
 2 UIApplicationMain@[native code]
 3 anonymous@file:///app/index.js:21:18
 4 __executeModule@require.js:127:27
 5 __loadModule@require.js:155:24
 6 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)@[native code]
 7 ffi_closure_SYSV_inner@[native code]
 8 .LCFI7@[native code]
 9 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:]@[native code]
10 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:]@[native code]
11 -[UIApplication _runWithMainScene:transitionContext:completion:]@[native code]
12 __84-[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:]_block_invoke3171@[native code]
13 -[UIApplication workspaceDidEndTransaction:]@[native code]
14 __37-[FBSWorkspace clientEndTransaction:]_block_invoke_2@[native code]
15 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke@[native code]
16 -[FBSSerialQueue _performNext]@[native code]
17 -[FBSSerialQueue _performNextFromRunLoopSource]@[native code]
18 FBSSerialQueueRunLoopSourceHandler@[native code]
19 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__@[native code]
20 __CFRunLoopDoSources0@[native code]
21 __CFRunLoopRun@[native code]
22 CFRunLoopRunSpecific@[native code]
23 CFRunLoopRunInMode@[native code]
24 -[UIApplication _run]@[native code]
25 UIApplicationMain@[native code]
26 .LCFI1@[native code]
27 ffi_call@[native code]
28 NativeScript::FFICall::call(JSC::ExecState*)@[native code]
29 JSC::LLInt::handleHostCall(JSC::ExecState*, JSC::Instruction*, JSC::JSValue, JSC::CodeSpecializationKind)@[native code]
30 JSC::LLInt::setUpCall(JSC::ExecState*, JSC::Instruction*, JSC::CodeSpecializationKind, JSC::JSValue, JSC::LLIntCallLinkInfo*)@[native code]
31 JSC::LLInt::genericCall(JSC::ExecState*, JSC::Instruction*, JSC::CodeSpecializationKind)@[native code]
32 llint_slow_path_call@[native code]
33 llint_entry@[native code]
34 llint_entry@[native code]
35 llint_entry@[native code]
36 ?@[native code]
```

image

**Comment by fealebenpae** [comment]
I don't think it looks right with the native stack trace in the inspector - the frames are out of order, unfortunately. Maybe we should disable gathering the native stack trace in the inspector?

I guess we can just stick with something more verbose, like I outlined in https://github.com/NativeScript/ios-runtime/pull/403#issuecomment-155739389.

**Comment by jasssonpet** [comment]
How does it look now:

```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x82ca2 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*)
2   0xbd60e NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0xc29726 ffi_closure_SYSV_inner
4   0xc29172 .LCFI7
5   0x27ca5fb -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:]
6   0x27cba29 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:]
7   0x27d2ec6 -[UIApplication _runWithMainScene:transitionContext:completion:]
8   0x27f6905 __84-[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:]_block_invoke3171
9   0x27cfbae -[UIApplication workspaceDidEndTransaction:]
10  0x699cccc __37-[FBSWorkspace clientEndTransaction:]_block_invoke_2
11  0x699c7a3 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke
12  0x69ba1cb -[FBSSerialQueue _performNext]
13  0x69ba602 -[FBSSerialQueue _performNextFromRunLoopSource]
14  0x69b98fe FBSSerialQueueRunLoopSourceHandler
15  0x4969e7f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
16  0x495fb0b __CFRunLoopDoSources0
17  0x495ef28 __CFRunLoopRun
18  0x495e866 CFRunLoopRunSpecific
19  0x495e67b CFRunLoopRunInMode
20  0x27cf497 -[UIApplication _run]
21  0x27d4cc1 UIApplicationMain
22  0xc2908d .LCFI1
23  0xc2966f ffi_call
24  0x50a48 NativeScript::FFICall::call(JSC::ExecState*)
25  0x7e10b1 JSC::LLInt::handleHostCall(JSC::ExecState*, JSC::Instruction*, JSC::JSValue, JSC::CodeSpecializationKind)
26  0x7e24cd JSC::LLInt::setUpCall(JSC::ExecState*, JSC::Instruction*, JSC::CodeSpecializationKind, JSC::JSValue, JSC::LLIntCallLinkInfo*)
27  0x7e2418 JSC::LLInt::genericCall(JSC::ExecState*, JSC::Instruction*, JSC::CodeSpecializationKind)
28  0x7de48f llint_slow_path_call
29  0x7e88eb llint_entry
30  0x7e88ff llint_entry
31  0x7e88ff llint_entry
JavaScript stack trace:
0   throwErrorFunction@file:///app/index.js:2:29
1   applicationDidFinishLaunchingWithOptions@file:///app/index.js:12:27
2   UIApplicationMain@[native code]
3   anonymous@file:///app/index.js:21:18
4   __executeModule@require.js:127:27
5   __loadModule@require.js:155:24
JavaScript error:
file:///app/index.js:2:29: JS ERROR Error: sample error
```

image

**Comment by fealebenpae** [comment]
I like how it looks now, I think it's more informative. Hopefully people will take the time to read it.

**Comment by jasssonpet** [comment]
ping @ivanbuhov :smile:

**Comment by ivanbuhov** [comment]
:+1:

**Pull request merged**
