### PR TITLE
Fix window dragging on El Capitan

### PR DESCRIPTION
**Pull request by KristinaKoeva**

### CODE REVIEW

**Comment by KristinaKoeva** [comment]
Would somebody that hasn't upgraded to El Capitan verify whether this is working for older OS too :)

**Comment by jasssonpet** [comment]
It's working for me (OS X Yosemite), but I think that the preprocessor check is always false, because our `MACOSX_DEPLOYMENT_TARGET` is 10.10.

**Comment by KristinaKoeva** [comment]
You are completely right, I blindly copy pasted this check from webkit source :disappointed: I will remove it so that you could test again

**Comment by jasssonpet** [comment]
The `startWindowDrag` is not being called, so I suspect everything is working :smile:

**Comment by KristinaKoeva** [comment]
This one https://github.com/NativeScript/ios-runtime/blob/master/src/debugging/WebInspectorUI/Base/Main.js#L1562 takes care of it :smiley_cat:

**Comment by jasssonpet** [comment]
BTW, it seems that #421 won't make it to the 1.5.1 milestone, so maybe you'll have to build the Inspector manually one last time.

**Pull request merged**
