### PR TITLE
Expose build configuration as an enviromental variable

### PR DESCRIPTION
**Pull request by jasssonpet**
One way to read it from JavaScript:

```javascript
NSProcessInfo.processInfo().environment.objectForKey('BUILD_CONFIGURATION'); // Debug, Release, ...
```

ping @PanayotCankov

### CODE REVIEW

**Comment by jasssonpet** [comment]
@PanayotCankov  It would be interesting if we could also reuse something like [envify](https://github.com/hughsk/envify) to completely strip debugging code during minification in release builds.

**Comment by fealebenpae** [comment]
Why do we need this?

**Comment by PanayotCankov** [comment]
@fealebenpae There is some extensive logging and debug information that we do not want to generate when the app is built for release.
@jasssonpet The suggestion looks cool, we'll have that in mind.

**Comment by fealebenpae** [comment]
@PanayotCankov I'm hesitant to involve the runtime in this, especially since this adds further complexity to the Xcode project template. Have you considered a CLI-based solution instead?

**Comment by PanayotCankov** [comment]
@fealebenpae Yes, I too share your concerns. If we introduce this in the CLI we will move the complexity from the runtime to the CLI. Then we will bind some of the debugging functionality to the CLI, rendering it inaccessible when using Xcode only from the Xcode project generated in the platforms/ios. Currently I can leave the debugging info enabled and worry about switching it on and off at a later stage, probably there are other solutions (like treating *.release.js and *.debug.js files in the CLI). If you think you'll be bothered too much supporting @jasssonpet's suggestion please feel free to reject the PR.

**Comment by fealebenpae** [comment]
My chief concern is that we've introduced enough complexity in the template to handle the various quirks of the CLI, its plugin system, and CocoaPods to boot. Adding more on top of that would make it even harder to use the runtime in an existing application since all of the template's complexity would have to be added to the existing project.

Now, if the CLI supported adding raw source files as part of a plugin (similarly to Cordova plugins), `nativescript-core-modules` could conceivably include a dummy header file that exports the build configuration as a constant:
```
#ifndef NDEBUG
static const BOOL TNSCoreModulesDebug = YES;
#else
static const BOOL TNSCoreModulesDebug = NO;
#endif
```

**Comment by PanayotCankov** [comment]
The CLI already treats the tns-core-modules as a plugin and I think we will be soon shipping the android "widgets" JAR that has the layout implementation as part of the modules. So shipping the header you mention in the tns-core-modules will actually be pretty neat. Do you want to discuss further what have to be done in the CLI in order to allow raw source files in the plugins?

**Comment by fealebenpae** [comment]
Yes, let's loop @teobugslayer on this IRL. I'll close this for the time being.

**Comment by PanayotCankov** [comment]
@fealebenpae :+1:

**Pull request closed without merging**
