### PR TITLE
fix(runtime): Use NSLog for dumping each line of callstack on crash

### LINKED ISSUE #565: Missing stack trace with async mocha tests
Reproduced with NativeScript 2.0.
## Execute the following commands:

``` shell
$ tns create TestApp
$ tns test init
$ tns test ios --emulator
```
## Add the following test:

``` javascript
describe('Test', function () {
    it('Test', function (done) {
        setTimeout(function() {
            assert.equal(-1, 1);
            done();
        }, 1000);
    });
});
```
## The output is:

```
1   0xe0050 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x7a7c50 ffi_closure_inner
3   0x7a85a2 ffi_closure_i386
4   0x380c136 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
5   0x380bb32 __CFRunLoopDoTimer
6   0x37ca39a __CFRunLoopRun
7   0x37c9846 CFRunLoopRunSpecific
8   0x37c965b CFRunLoopRunInMode
9   0x5573664 GSEventRunModal
10  0x55734a1 GSEventRun
11  0x1568eb9 UIApplicationMain
12  0x7a8468 ffi_call_i386
undefined: JS ERROR AssertionError: expected -1 to equal 1
```
## Expected

The JavaScript stack trace should be printed along with the `sourceURL` for the `AssertionError`.

Ping @ginev

### PR DESCRIPTION
**Pull request by mbektchiev**
* NSLog writes to both the Apple System Log and stderr. The change is necessary
because CLI watches ASL for messages
* CLI's parser cannot parse multi-line messages and we need to rewrite it. Meanwhile
we can workaround it by calling NSLog once for every line being logged.

fixes #565

### CODE REVIEW

**Comment by Natalia-Hristova** [comment]
run ci

**Comment by mbektchiev** [comment]
run ci

**Comment by mbektchiev** [comment]
run ci

**Comment by mbektchiev** [comment]
run ci

**Comment by mbektchiev** [comment]
run ci

**Comment by mbektchiev** [comment]
run ci

**Pull request merged**
