### PR TITLE
Update WebKit to version ios-11

### PR DESCRIPTION
**Pull request by mbektchiev**
Update WebKit to the latest official release so far -- [~~iOS 11.0~~](https://trac.webkit.org/browser/webkit/releases/Apple/iOS%2011.0?order=date&desc=1) [iOS 11.2.5](https://trac.webkit.org/browser/webkit/releases/Apple/iOS%2011.2.5?order=date&desc=1)

### CODE REVIEW

**Comment by mbektchiev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by mbektchiev** [comment]
run ci

**Comment by Natalia-Hristova** [comment]
run ci

**Comment by ginev** [comment]
run ci

**Comment by Natalia-Hristova** [comment]
run ci

**Comment by ginev** [comment]
With the current state of the code the tns-ios-inspector-pr build can successfully run on a Mac OS X Sierra with Xcode 8. If we want to build on Mac OS X High Sierra with Xcode 9 we will not be able to support the iOS Inspector on Mac OS X Sierra and earlier. We need to decide how to handle this.

**Comment by Natalia-Hristova** [comment]
run ci

**Comment by Natalia-Hristova** [comment]
run ci

**Pull request merged**
