### PR TITLE
chore: add development team and provisioning profile

### PR DESCRIPTION
**Pull request by vchimev**
The CI build started failing after updating our certificates because it can't find a provisioning profile to sign the test app.
This change specifies development team and provisioning profile in the generated native project, required for code signing.
Both variables come as environment variables in the CI system.
In addition, both variables could be extracted as script parameters for easier local development.

### CODE REVIEW

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by zahhak** [comment]
Please add more information that answers the following questions:

- What is the reasoning for this change?
- Why do we exactly want to fix it this way?

**Comment by zahhak** [comment]
@vchimev Great job! ;)

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
The *default* check fails due to a failure in the `master` branch.

**Comment by zahhak** [comment]
@mbektchiev Could you please check if you can use the Gamera/Blank project without provisions (in the simulator)? (with this change included)

**Comment by mbektchiev** [comment]
Yes, I just checked and they are building successfully.

**Pull request merged**
