### PR TITLE
Add the NativeScript.framework to the tns-ios

### PR DESCRIPTION
**Pull request by PanayotCankov**
See #96

### CODE REVIEW

**Comment by ivanbuhov** [comment]
:+1:

**Comment by fealebenpae** [comment]
Why is it copying the Debug build of the framework?

**Comment by fealebenpae** [comment]
Could you please reopen this and change the build scripts to indicate that this is actually packaging the device+simulator build of the framework, rather than the debug build?

**Comment by PanayotCankov** [comment]
We have Debug and Release folders where the Debug has the following architectures: i386, x86_64, armv7, arm64, and the Release has only the: armv7, arm64... since we can strip the simulator architectures on build, I do not think that we actually need 2 versions of the framework at all.

We will probably further polish the CMake build when @jasssonpet is back. You can log it if you are afraid we will forgot that.

For now I just need to complete the #96 iOS Extensions issue

**Comment by jasssonpet** [comment]
We should remove the build with arm architectures only, because we now strip the non valid architectures on build.

**Pull request merged**
