### PR TITLE
tvOS build

### PR DESCRIPTION
**Pull request by jasssonpet**
Now that everything is built from source, we can add tvOS to the list of supported platforms.

```
CONSOLE LOG terminal_reporter.js:25:20: SUCCESS: 482 specs, 0 failures, 0 skipped, 0 disabled in 55.01s.
```

:fireworks:

### CODE REVIEW

**Comment by jasssonpet** [comment]
run ci

**Comment by fealebenpae** [comment]
I'm afraid that the current version of Clang isn't able to generate metadata for the tvOS SDK without external modifications. Clang 3.8, due in February, should be able to handle tvOS, though, so I suggest we freeze this and revisit it when we switch to Clang 3.8.

**Comment by jasssonpet** [comment]
test comment

**Comment by jasssonpet** [comment]
Moved to https://github.com/NativeScript/ios-runtime/pull/602

**Comment by BigLep** [comment]
Has there been any change on this?  Let me know if should be looking somewhere else, but wanted to inquire on the tvOS development plans given this thread is ~2 years old.

**Comment by radeva** [comment]
Hi @BigLep ,

Currently tvOS is not part of our immediate plans, we focus mainly on iOS and Android. You can follow [NativeScript roadmap](https://www.nativescript.org/roadmap-and-releases#releases) for any future updates on the topic.

**Pull request closed without merging**
