### PR TITLE
Add notifications so that clients will know when the app is going to resign or become active

### PR DESCRIPTION
**Pull request by KristinaKoeva**
https://github.com/NativeScript/ios-runtime/issues/189

### CODE REVIEW

**Comment by fealebenpae** [comment]
Please wrap the UIKit-specific code in `#if PLATFORM(IOS)` blocks. Hopefully this will run on OS X before the turn of the next millennium.

**Comment by KristinaKoeva** [comment]
We are probably going to need a different project template for OS X. Moreover ```#if PLATFORM(IOS)``` is defined in ```wtf\\Platform.h``` which is not available for the template. We could use ```#if TARGET_OS_IPHONE``` but as you saw the logic would become a little bit complicated so if you don't mind I will leave it as it is.

**Comment by KristinaKoeva** [comment]
run ci

**Comment by fealebenpae** [comment]
@KristinaKoeva: You're right, we could end up needing a separate template for OS X apps anyway.

**Pull request merged**
