### PR TITLE
Remove NSNotificationCenter blocks-based API usage

### LINKED ISSUE #229: Crash in TNSRuntime dealloc
Happens in iOS 8 and iOS 9 simulators:

`EXC_BAD_ACCESS`: https://github.com/NativeScript/ios-runtime/blob/afcd175dc22ce6024af8cd45970c5df31c3ae4e9/src/NativeScript/TNSRuntime.mm#L137

### PR DESCRIPTION
**Pull request by fealebenpae**
Removing an observer added with
`-[NSNotificationCenter addObserverForName:object:queue:usingBlock:]` crashes. Replace with the old, boring `-[NSNotificationCenter addObserver:selector:name:object:]` instead.
Fixes #229

### CODE REVIEW

**Comment by fealebenpae** [comment]
ping @jasssonpet

**Comment by jasssonpet** [comment]
Is the `_memoryPressureNotificationSubscription` field needed now?

**Comment by fealebenpae** [comment]
It's not, I had forgotten to remove it.

**Comment by fealebenpae** [comment]
run ci

**Comment by jasssonpet** [comment]
:+1:

**Pull request merged**
